rtm-naming modified for macOS. rtm-naming_cmake.in moved to rtm-naming.in. CMakelists.txt modified.

diff --git a/utils/rtm-naming/rtm-naming.in b/utils/rtm-naming/rtm-naming.in
--- a/utils/rtm-naming/rtm-naming.in
+++ b/utils/rtm-naming/rtm-naming.in
@@ -1,23 +1,22 @@
+#!/bin/bash
 #
 #  @file rtm-naming
 #  @brief OpenRTM-aist name server launcher
-#  @date $Date: 2005-05-12 09:06:19 $
 #  @author Noriaki Ando <n-ando@aist.go.jp>
 #
-#  Copyright (C) 2003-2018
-#      Intelligent Systems Research Institute,
+#  Copyright (C) 2003-2020
 #      National Institute of
 #          Advanced Industrial Science and Technology (AIST), Japan
 #      All rights reserved.
 #
-#  $Id$
-#
 
+COSNAMES="@COSNAMES@"
+ORB="@CORBA@"
 PNAME=`basename $cosnames`
 HOSTNAME=`hostname`
 OSNAME=`uname -s`
 LOGDIR="/tmp"
-DEBUG=""
+DEBUG="YES"
 
 usage()
 {
@@ -83,7 +82,7 @@ get_opt()
 debug()
 {
     if test "x$DEBUG" != "x"; then
-        echo $* >> /tmp/rtm-naming_debug.log
+        echo $* >> /tmp/rtm-naming-${USER}_debug.log
     fi
 }
 
@@ -144,7 +143,7 @@ get_pid_of_nsport_macos()
 {
     debug "get_pid_of_nsport_macos()"
     _port=$1
-    debug "lsof -n -P -i :$_port | grep LISTEN"
+    debug "sudo -S lsof -n -P -i :$_port | grep LISTEN"
     if test "x$PASSWORD" = "x"; then
         _netstat=`sudo -S lsof -n -P -i :$_port | grep LISTEN`
     else
@@ -236,14 +235,28 @@ check_cosname()
 delete_omninames_files()
 {
     debug "delete_omninames_files()"
+    _logfiles=(
+        $LOGDIR/omninames-$HOSTNAME.log
+        $LOGDIR/omninames-$HOSTNAME.bak
+        $LOGDIR/omninames-$HOSTNAME.dat
+        )
     if test "x$PASSWORD" = "x" ; then
-        rm -f $LOGDIR/omninames-$HOSTNAME.log
-        rm -f $LOGDIR/omninames-$HOSTNAME.bak
-        rm -f $LOGDIR/omninames-$HOSTNAME.dat
+        for file in ${_logfiles[@]} ; do
+            if test -w $file ; then
+                rm -f $file
+            else
+                debug "log files are not writable. delete by sudo."
+                sudo -S rm -f $file
+            fi
+        done
     else
-        echo $PASSWORD | sudo -S rm -f $LOGDIR/omninames-$HOSTNAME.log
-        echo $PASSWORD | sudo -S rm -f $LOGDIR/omninames-$HOSTNAME.bak
-        echo $PASSWORD | sudo -S rm -f $LOGDIR/omninames-$HOSTNAME.dat
+        for file in ${_logfiles[@]} ; do
+            echo $PASSWORD | sudo -S rm -f $file
+        done
+    fi
+    if test $? != 0 ; then
+        echo "Delete log files failed!!"
+        debug "Delete log files failed!!"
     fi
     debug "omninames-$HOSTNAME files deleted."
 }
@@ -255,7 +268,7 @@ delete_omninames_files()
 #
 specified_port_used_check()
 {
-    debug "pecified_port_used_check()"
+    debug "specified_port_used_check()"
     if test "x$OSNAME" = "xDarwin" ; then
         get_pid_of_nsport_macos $PORT
     else
@@ -363,12 +376,14 @@ stop_existing_ns()
                 fi
 	        fi
             if test "x$PASSWORD" = "x" ; then
+                debug "Killing name service. PID = " $pid_of_nsport
                 sudo kill -9 $pid_of_nsport
             else
+                debug "Killing name service. PID = " $pid_of_nsport
                 echo $PASSWORD | sudo -S kill -9 $pid_of_nsport
             fi
-            echo "$PNAME (pid: $pid_of_nsport) are killed"
-            debug "$PNAME (pid: $pid_of_nsport) are killed"
+            echo "$PNAME (pid: $pid_of_nsport) is killed"
+            debug "$PNAME (pid: $pid_of_nsport) is killed"
             delete_omninames_files
             return 0
         fi
@@ -397,13 +412,9 @@ start_omninames()
     echo  'Starting omniORB omniNames: '$HOSTNAME':'$PORT
     debug 'Starting omniORB omniNames: '$HOSTNAME':'$PORT
     delete_omninames_files
-    if test "x$PASSWORD" = "x" ; then
-        debug "$cosnames -start $PORT -logdir $LOGDIR"
-        $cosnames -start $PORT -logdir $LOGDIR &
-    else
-        debug "echo $PASSWORD | sudo -S $cosnames -start $PORT -logdir $LOGDIR"
-        echo $PASSWORD | sudo -S $cosnames -start $PORT -logdir $LOGDIR &
-    fi
+
+    debug "$cosnames -start $PORT -logdir $LOGDIR"
+    $cosnames -start $PORT -logdir $LOGDIR &
     if test $? != 0; then
         debug "omniNames start failed."
         return 1
@@ -423,10 +434,13 @@ start_omninames()
     # check if the omniNames strill working
     omnipid=`ps $pid | grep $pid | grep -v grep | awk '{print $1;}'`
     debug   "omnipid: "$omnipid
-    if test "x$omnipid" != "x" -a $omnipid -gt 1; then
+    if test "x$omnipid" != "x" ; then
         debug "omniNames properly started"
         echo  "omniNames properly started"
         exit 0
+    else
+        debug "omniNames start failed."
+        echo  "omniNames start failed."
     fi
     return 1 
 }
@@ -439,8 +453,8 @@ omniname()
 
     # Starting omniNames 
     if test "x$STOPNAMESERVICE" = "x" ; then
-      start_omninames
-      echo "omniNames was not properly started."
+        start_omninames
+        echo "omniNames was not properly started."
     fi
 
     # Stopping existing name service
@@ -448,8 +462,8 @@ omniname()
 
     # Try to start omniNames again
     if test "x$STOPNAMESERVICE" = "x" ; then
-      start_omninames
-      echo "omniNames was not properly started."
+        start_omninames
+        echo "omniNames was not properly started."
     fi
 }
 
@@ -519,4 +533,3 @@ case $orb in
 		usage
 		;;
 esac
-
